In [1]:
import piplite
await piplite.install('seaborn')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
#Load the data

In [4]:
data = pd.read_csv('11 real estate price size year.csv')

In [5]:
data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [6]:
#Declare independent and dependent variables

In [7]:
x = data[['size', 'year']]
y = data['price']

In [8]:
#Standardization sklearn

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

In [11]:
scaler.fit(x)

StandardScaler()

In [12]:
x_scaled = scaler.transform(x)
x_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

In [13]:
#Regression with scaled features

In [14]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [15]:
reg.coef_

array([67501.57614152, 13724.39708231])

In [16]:
reg.intercept_

292289.4701599997

In [17]:
#Create summary table

In [18]:
reg_summary = pd.DataFrame(data=[['Bias'], ['size'], ['year']], columns=['features'])

In [19]:
reg_summary

features
0     Bias
1     size
2     year

In [21]:
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [22]:
reg_summary

features        Weights
0     Bias  292289.470160
1     size   67501.576142
2     year   13724.397082

In [23]:
#Make predictions

In [28]:
new_data = pd.DataFrame(data = [[750,2009],[800,2019]], columns=['size', 'year'])

In [29]:
new_data

size  year
0   750  2009
1   800  2019

In [30]:
#Standardize new data

In [31]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-0.34752816, -0.76509206],
       [-0.1788648 ,  1.36016365]])

In [32]:
reg.predict(new_data_scaled)

array([258330.34465995, 298883.2406287 ])

In [34]:
new_data['predicted price'] = reg.predict(new_data_scaled)[0], reg.predict(new_data_scaled)[1]

In [35]:
new_data

size  year  predicted price
0   750  2009    258330.344660
1   800  2019    298883.240629