In [1]:
import piplite
await piplite.install('seaborn')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
#Load The Data

In [4]:
data = pd.read_csv('09 Multiple linear regression.csv')

In [5]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [6]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [7]:
#Create Regression

In [8]:
#Declare variable

In [9]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [10]:
#Regression

In [11]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [12]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [13]:
reg.intercept_

0.29603261264909486

In [14]:
#Calculate R-Squared

In [15]:
reg.score(x,y)

0.40668119528142843

#Formula for adj R-squared

$R^2_{adj.} = 1 - (1-R^2)\frac{n-1}{n-p-1}$

In [16]:
x.shape

(84, 2)

In [17]:
r2 = reg.score(x,y)

n = x.shape[0]

p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

In [18]:
#Feature Selection

In [19]:
from sklearn.feature_selection import f_regression

In [20]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [21]:
#Output of f_regression : first array is F-stats and second array is p-values

In [22]:
p_values = f_regression(x,y)[1]

In [23]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [24]:
p_values.round(3)

array([0.   , 0.676])

In [25]:
#from p value we know which useful variable is if p-values <0.05

In [26]:
#Creating summary table

In [28]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [30]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [31]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676