In [1]:
#Import relevant library

In [2]:
import piplite
await piplite.install('seaborn')

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [4]:
#Generate random input data to train

In [5]:
observations = 1000

xs = np.random.uniform(low=-10,high=10, size=(observations,1))
zs = np.random.uniform(-10,10,(observations,1))

inputs = np.column_stack((xs,zs))

inputs.shape

(1000, 2)

In [6]:
#Create the target we will aim at
#  targets = f(x,z) = 2*x - 3*z + 5 + noise

In [7]:
noise = np.random.uniform(-1,1,(observations,1))

targets = 2*xs - 3*zs + 5 + noise

In [8]:
targets.shape

(1000, 1)

In [9]:
#Plot the data

In [10]:
#initialize variables

In [11]:
init_range = 0.1

weights = np.random.uniform(-init_range, init_range, size=(2,1))

biases = np.random.uniform(-init_range, init_range, size=1)

weights

array([[-0.09005064],
       [ 0.01068417]])

In [12]:
biases

array([-0.02706671])

In [13]:
#Desain learning rate

In [14]:
learning_rate = 0.02

In [15]:
#Train the model

In [16]:
for i in range(100):
    outputs = np.dot(inputs,weights) + biases
    deltas = outputs - targets
    
    loss = np.sum(deltas ** 2) / 2 / observations
    
    print (loss)
    
    deltas_scaled = deltas / observations
    
    weights = weights - learning_rate * np.dot(inputs.T, deltas_scaled)
    biases = biases - learning_rate * np.sum(deltas_scaled)

222.61575229631808
42.034849106320124
15.9925418635006
11.900278609448389
10.942680132965483
10.445750784347325
10.028649949750172
9.636625861257773
9.261342627569139
8.901092030734485
8.555130018342137
8.222869648486238
7.90376539586006
7.597295923381963
7.302960904586445
7.020279875583647
6.748791403591075
6.488052326998089
6.237637031018426
5.997136752805962
5.76615891419545
5.544326480878806
5.331277346956631
5.126663743858295
4.930151672665478
4.7414203589124435
4.56016172897313
4.386079907180329
4.218890732856072
4.058321296464848
3.9041094941325354
3.756003599803815
3.613761854339739
3.4771520708846593
3.3459512558584037
3.2199452449549932
3.0989283535537195
2.9827030409719764
2.8710795880117446
2.7638757872733963
2.660916645731321
2.5620340990858574
2.467066737425248
2.37585954174982
2.2882636309283244
2.204136018673332
2.1233393801390403
2.0457418277604713
1.971216695968148
1.899642334426851
1.8309019094609504
1.7648832133421415
1.701478481128314
1.6405842147545509
1.582101014

In [23]:
weights

array([[ 2.00331924],
       [-3.0016926 ]])

In [24]:
biases

array([4.32361686])