In [1]:
import piplite
await piplite.install('seaborn')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [4]:
#Load the data

In [5]:
data = pd.read_csv('11 real estate price size year.csv')

In [6]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [7]:
data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [8]:
#Create regression

In [9]:
x = data[['size', 'year']]
y = data['price']

In [10]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [11]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [12]:
reg.intercept_

-5772267.017463278

In [13]:
#Calculate R-squared

In [14]:
reg.score(x,y)

0.7764803683276795

#Formula for adj R-squared

$R^2_{adj.} = 1 - (1-R^2)\frac{n-1}{n-p-1}$

In [15]:
adjusted_r2 = 1-(1-reg.score(x,y))*(x.shape[0]-1)/[x.shape[0]-x.shape[1]-1]

In [16]:
adjusted_r2

array([0.77187172])

In [17]:
#Feature selection

In [18]:
from sklearn.feature_selection import f_regression

In [19]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [20]:
p_values = f_regression(x,y)[1]

In [21]:
p_values.round(3)

array([0.   , 0.357])

In [22]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0     size
1     year

In [23]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [24]:
reg_summary

Features  Coefficients  p-values
0     size    227.700854     0.000
1     year   2916.785327     0.357